# ~/.config/starship.toml

format = """
$username$hostname$directory$git_branch$git_status$cmd_duration$package$memory_usage$status$kubernetes$battery
$character
"""

scan_timeout = 5000
command_timeout = 5000
add_newline = true

[character]
disabled = false
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
#vimcmd_symbol  = "[❮](bold yellow)"
vimcmd_symbol = '[V](bold green) '

[username]
disabled = false
show_always = false
format = "[$user]($style) "
#style_user = "bold cyan"
style_root = "bold red"
#style_root = "bold white bg:red"

[hostname]
disabled = true
ssh_only = false
format = "[$hostname ]($style)"
style = "bold yellow"
#trim_at = "-"

[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style) "
#style = "bold blue"
style = "bold cyan"
truncation_length = 4
truncate_to_repo = true
read_only = " 🔒"

[package]
disabled = false 
format = "[📦 $version]($style) "
style = "white"

[git_branch]
disabled = false
format = "on [$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
disabled = false
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold white)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[kubernetes]
disabled = false
detect_files = ['k8s']

[java]
disabled = true
format = "[☕ $version]($style) "
style = "bold red"

[perl]
disabled = true

[cmd_duration]
disabled = false
min_time = 50
format = "took [$duration]($style) "
style = "bold yellow"
#show_milliseconds = true

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✖ "
success_symbol = ""
not_executable_symbol = "⚡"
not_found_symbol = "⚡"
sigint_symbol = "⚡"
signal_symbol = "⚡"
style = "bold red"
map_symbol = true

[battery]
charging_symbol = "⚡"
disabled = false
discharging_symbol = "🪫"
empty_symbol = "🪫"

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[memory_usage]
disabled = false
threshold = 80
format = "[🧮 ${ram_pct}]($style) "
style = "bold dimmed green"


