# brew bundle --file=Brewfile

# --- development ---
cask "wezterm"
cask "termius"
cask "intellij-idea"
cask "docker-desktop"
cask "antigravity-ide"
cask "visual-studio-code"
cask "zed"
cask "dbeaver-community"
cask "postman"
# cask "datagrip"
# cask "sublime-text"

# --- notes ---
cask "obsidian"
cask "todoist-app"
tap "zennotes/tap"; cask "zennotes/tap/zennotes"
cask "notion"
cask "wispr-flow"

# --- web ---
cask "claude"
cask "chatgpt"
cask "arc"

# --- cli-tools ---
brew "starship"
brew "stow"
brew "git"
brew "eza"
brew "fzf" # fzf-git requires manual install
brew "tmux"
brew "nvim"
brew "bat"
brew "fd"
brew "ripgrep"
brew "zoxide"
brew "yazi"
brew "btop"
brew "ctop"
brew "ncdu"
brew "jq"
brew "yq"
brew "fastfetch"
brew "nerdfetch"
brew "git-delta"
brew "lazygit"
brew "lazydocker"
brew "atuin"
brew "glow"
brew "k6"
brew "trash"
# brew "awscli"

# --- kubernetes ---
# brew "kubectl"
# brew "helm"
# brew "k9s"
# brew "kubectx"
# brew "argocd"

# --- fonts ---
cask "font-meslo-lg-nerd-font"

# --- mac utils ---
cask "raycast"
cask "maccy" # https://github.com/p0deje/Maccy/blob/master/README.md#usage
cask "monitorcontrol"
cask "appcleaner"
# tap "nikitabobko/tap"; cask "nikitabobko/tap/aerospace"
# cask "fliqlo" # broken, install manually
# cask "iina" # better vlc
# cask "skim" # pdf reader
# cask "dropzone"

# --- manual installation ---
# logitech logi-options+
# sdkman: curl -s "https://get.sdkman.io" | bash
# davinci resolve
