# Brewfile - commented tools are not to be installed 

# --- terminal ---
cask "wezterm"
cask "termius"

# --- notes ---
cask "obsidian"
cask "notion"
cask "todoist-app"
cask "sublime-text"
tap "zennotes/tap"
cask "zennotes/tap/zennotes"

# --- editors ---
cask "intellij-idea"
cask "antigravity-ide"
cask "visual-studio-code"
cask "zed"
cask "sublime-merge"

# --- databases ---
cask "dbeaver-community"
# cask "datagrip"

# --- utils ---
# cask "raycast" # https://www.raycast.com/
cask "maccy" # https://github.com/p0deje/Maccy/blob/master/README.md#usage

# --- web ---
cask "claude"
cask "chatgpt"
# cask "google-chrome"
cask "arc"
cask "zen"

# --- Shell / dotfiles / core CLI ---
brew "starship"
brew "stow"
brew "git"
brew "eza"
brew "fzf" # fzf-git requires manual install
brew "tmux"
brew "nvim"
brew "bat"
brew "fd"
brew "ripgrep"
brew "zoxide"
brew "yazi"
brew "btop"
brew "ctop"
brew "ncdu"
brew "jq"
brew "yq"
brew "fastfetch"
brew "nerdfetch"
brew "git-delta"
brew "lazygit"
brew "atuin"

# --- java ---
# sdkman: curl -s "https://get.sdkman.io" | bash

# --- fonts ---
cask "font-meslo-lg-nerd-font"

# --- containers ---
cask "docker-desktop"
brew "lazydocker"

# --- Kubernetes ---
# brew "kubectl"
# brew "helm"
# brew "k9s"
# brew "kubectx"
# brew "argocd"

# --- Kafka ---
# brew "kafka"

# --- cloud ---
# brew "awscli"

# --- video editing ---
# davinci resolve

# --- mac utils ---
# cask "fliqlo"
cask "alt-tab"
# cask "dropzone"
cask "monitorcontrol" # control ext display
cask "appcleaner"
# cask "iina" # better vlc
# cask "skim" # pdf reader

