# Brewfile - commented tools are not to be installed 
# brew bundle --file=Brewfile

# --- notes ---
cask "obsidian"
cask "todoist-app"
cask "sublime-text"
cask "sublime-merge"
tap "zennotes/tap"; cask "zennotes/tap/zennotes"
cask "notion"

# --- development ---
cask "wezterm"
cask "termius"
cask "intellij-idea"
cask "docker-desktop"
cask "antigravity-ide"
cask "visual-studio-code"
cask "zed"
cask "sublime-merge"
cask "dbeaver-community"
# cask "datagrip"

# --- mac utils ---
cask "maccy" # https://github.com/p0deje/Maccy/blob/master/README.md#usage
cask "raycast"
tap "nikitabobko/tap"; cask "nikitabobko/tap/aerospace"
cask "monitorcontrol" # control ext display
cask "appcleaner"
# cask "fliqlo" # broken, install manually
# cask "iina" # better vlc
# cask "skim" # pdf reader
# cask "dropzone"
# cask "caffine"

# --- web ---
cask "claude"
cask "chatgpt"
cask "arc"
cask "zen"

# --- cli-tools ---
brew "starship"
brew "stow"
brew "git"
brew "eza"
brew "fzf" # fzf-git requires manual install
brew "tmux"
brew "nvim"
brew "bat"
brew "fd"
brew "ripgrep"
brew "zoxide"
brew "yazi"
brew "btop"
brew "ctop"
brew "ncdu"
brew "jq"
brew "yq"
brew "fastfetch"
brew "nerdfetch"
brew "git-delta"
brew "lazygit"
brew "lazydocker"
brew "atuin"
brew "glow"
# brew "awscli"
# grafana-k6 testing tool

# --- fonts ---
cask "font-meslo-lg-nerd-font"

# --- kubernetes ---
# brew "kubectl"
# brew "helm"
# brew "k9s"
# brew "kubectx"
# brew "argocd"

# --- manual installation ---
# logitech logi-options+
# sdkman: curl -s "https://get.sdkman.io" | bash
# davinci resolve
#
